name: CD

on:
  push:
    branches:
      - master
      - prod

jobs:
  api-deploy:
    name: API Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          mask-aws-account-id: true

      - id: login-ecr
        name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set branch-level configuration
        run: |
          if [[ ${{ github.ref }} == "refs/heads/prod" ]]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_ENV
            echo "CLUSTER_NAME=${{ vars.AWS_ECS_API_CLUSTER_PROD }}" >> $GITHUB_ENV
            echo "SERVICE_NAME=${{ vars.AWS_ECS_API_SERVICE_PROD }}" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
            echo "CLUSTER_NAME=${{ vars.AWS_ECS_API_CLUSTER_STAGING }}" >> $GITHUB_ENV
            echo "SERVICE_NAME=${{ vars.AWS_ECS_API_SERVICE_STAGING }}" >> $GITHUB_ENV
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          GIT_SHA: ${{ github.sha }}
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPO: ${{ vars.AWS_ECR_API_REPO }}
        run: |
          # Check if image exists in ECR with GIT_SHA tag
          image_manifest=$(aws ecr batch-get-image --repository-name $REPO --image-ids imageTag=$GIT_SHA --query 'images[0].imageManifest' --output text)

          if [[ $image_manifest == "None" ]]; then
            echo "Image does not exist with tag \"$GIT_SHA\", building and pushing new image."
            docker build --platform linux/arm64 -t $REGISTRY/$REPO:$GIT_SHA -t $REGISTRY/$REPO:$IMAGE_TAG -f packages/daimo-api/Dockerfile .
            docker push $REGISTRY/$REPO:$GIT_SHA
            docker push $REGISTRY/$REPO:$IMAGE_TAG
          else
            echo "Image exists with tag \"$GIT_SHA\", adding tag \"$IMAGE_TAG\" to it."
            set +e
            output=$(aws ecr put-image --repository-name $REPO --image-tag $IMAGE_TAG --image-manifest "$image_manifest" 2>&1)
            status=$?
            set -e

            if [[ $status -ne 0 && ! "$output" =~ "ImageAlreadyExistsException" ]]; then
              echo $output
              exit $status
            else
              echo "Image already tagged with \"$IMAGE_TAG.\""
            fi
          fi

      - name: Deploy to ECS
        run: |
          pip install ecs-deploy
          ecs deploy $CLUSTER_NAME $SERVICE_NAME --timeout 900

  eas-deploy:
    if: github.ref == 'refs/heads/master'
    name: EAS Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install dependencies
        run: npm ci && npm test

      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v8
        with:
          packager: npm
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Build and publish update
        run: npm run build:prod
        working-directory: ./apps/daimo-mobile
