name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    needs: test-mobile
    runs-on: ubuntu-latest
    steps:
      - run: echo All tests passed

  test-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - id: cache
        uses: actions/cache@v3
        with:
          path: ./packages/daimo-mobile/node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci --ignore-scripts
        working-directory: ./packages/daimo-mobile
      - run: npm test
        working-directory: ./packages/daimo-mobile
