name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  FOUNDRY_PROFILE: ci

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci && npm test

  test-contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - run: forge test -vvv
        working-directory: ./packages/contract

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - run: npm ci && npm run lint
      # TODO: once https://github.com/wagmi-dev/wagmi/issues/2528 is fixed
      #   ... run npm run codegen && git diff --exit-code
