name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    needs: test-mobile
    runs-on: ubuntu-latest
    steps:
      - run: All tests passed

  test-mobile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"
      - run: npm ci
        working-directory: ./packages/daimo-mobile
      - run: npm test
        working-directory: ./packages/daimo-mobile
